config/routes.rb
Rails.application.routes.draw do
  get '/health', to: "health#index"
  get '/home', to: "home#index"
  get '/tour', to: "tour_spending#index"
  get '/status', to: "credential_checks#index"
  post '/api/add_user_and_password', to: 'api#add_user_and_password'
  get '/api/cron_update_check', "api#cron_update_check"
  post "/api/update_user_and_subscription", to: "api#update_user_and_subscription"
  
  get '/search', to: "search#index"
  get "/dates_and_times", to: "dates_and_times#index"
  

  resources :users, only: [:new, :create]
  
  get '/jobs/filter', "jobs#filter"
  resources :jobs
  resources :notes
  resources :cover_letters
  resources :tasks
  resources :reports
  resources :news_feed
  resources :deadlines
  resources :possible_times
  
  resources :tours
  # resources :setup_wizard
  # resources :tour_spending
  # resources :tour_other
  resources :job_search_urls
  
  # resources :credentials do
  #   member do
  #     get :test_password
  #   end
  # end
  #get "/credentials/test_password", to: "credentials#test_password"
  
  # resources :credential_checks
  # resources :purchases
  # resources :budgets
  # resources :alert_addresses

  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/health', to: "health#index"
  get '/health/df', to: "health#df"
  get '/health/hosts', to: "health#hosts"
  get "/health/who", to: "health#who"
  get "/signups/new", to: "users#new"
  

  get '/logout', to: 'user_sessions#destroy', as: :logout
  get '/login', to: 'user_sessions#new', as: :login
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  get "/signup", to: "signups#new", as: :signup
  
  
  # resources :api do
  #   get :usernames, to: 'api#usernames'
  # end
  
  # get "/api/usernames", to: "api#usernames"
  # get "/api/usernames_with_subscription_types", to: "api#usernames_with_subscription_types"
  # get "/api/subscription_type", to: "api#subscription_type"
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  # resources :me
  
  resources :pricing

  #mount RailsDb::Engine => '/rails/db', :as => 'rails_db'

  
  # resources :sources
  resources :signups
  root to: 'visitors#index'
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  remember_me(true)
  remember_me_for(30.days)
  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  
  ###skip_before_action :require_login, only: [:new, :create]
  
  def new
    @user_session = UserSession.new
  end

  def create
    #@user_session = UserSession.new(user_session_params)
    @user_session = UserSession.new(user_session_params.to_hash)
    #raise user_session_params.inspect
    if @user_session.save
      puts "Got into if condition success"
      flash[:success] = "Welcome back!"
      u_obj = User.where(:email => user_session_params["email"]).first
      l = Login.new
      l.date_created_at = Time.now
      l.user_id = u_obj.id
      l.login_type = "game_nanny_site"
      l.ip_address = request.remote_ip
      l.user_agent = request.user_agent
      if l.save
      else
        raise l.error.full_messages
      end
      
      #redirect_to "/home" and return
      redirect_back_or_default("/")
      #redirect_to "/home", success: "#{@user_session.inspect}" and return
    else
      puts "got into else failure condition "
      raise @user_session.errors.full_messages.inspect
      flash[:notice] = @user_session.errors.full_messages
      render :new
    end
    if l && l.user_id.nil?
      l.update_attribute(:user_id, u_obj.id)
    end
  end

  def destroy
    current_user_session.destroy
    flash[:success] = "Goodbye!"
    redirect_to root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password, :remember_me)
  end
end

app/views/user_sessions/_login.html.erb
  <%= form_for @user_session do |f| %>
    <%#= render 'shared/errors', object: @user_session %>
    
    <%#=f.hidden_field :login_type, :value => "hyde_web" %>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :remember_me %>
      <%= f.check_box :remember_me %>
    </div>
    <%= f.submit "Log in!", class: 'btn btn-primary btn-lg ', :style => "text-align: center" %>
    <br/><br/>
    <%#= link_to 'Forgot your password?', new_password_reset_path, class: 'btn btn-sm btn-default' %>
  <% end %>

app/views/user_sessions/_login_original.html.erb
  <%= form_for @user_session do |f| %>
    <%= render 'shared/errors', object: @user_session %>
    
    <%=f.hidden_field :login_type, :value => "hyde_web" %>

    <div class="form-group">
      <%= f.label :email_or_username %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :remember_me %>
      <%= f.check_box :remember_me %>
    </div>
    <%= f.submit "Log in!", class: 'btn btn-primary btn-lg ', :style => "text-align: center" %>
    <br/><br/>
    <%#= link_to 'Forgot your password?', new_password_reset_path, class: 'btn btn-sm btn-default' %>
  <% end %>

app/views/user_sessions/_sign_up.html.erb
<p>Signing up for <%= PRODUCT_NAME %> is easy and fast. You can sign up now and:</p>

  <ul>
  <li><strong>Make getting a good tech job suck less!</strong> 
  <li>Keep track of every job you apply for and where you are in the process
  <li>Organize all your job materials in one place whether cover letter, notes or answers to questions on web forms
  <li>Easily add jobs and automatically import them using our bookmarklet from leading tech job sites like Stack Overflow, Dice, Github and others
  <li>Search across everything with one easy query
</ul>

<div style="text-align:center">
  <%= link_to new_user_path, class: 'btn btn-primary btn-lg' do %>
    Sign Up Today! &raquo;
  <% end %>
</div>

app/views/user_sessions/_signup_original.html.erb
  <%= form_for @user_session do |f| %>
    <%= render 'shared/errors', object: @user_session %>
    
    <%#=f.hidden_field :signup, :value => "hyde_web" %>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :username %>
      <%= f.email_field :username, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.email_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>



    <%= f.submit "Sign Up!", class: 'btn btn-primary btn-lg' %>
    <br/><br/>
    <%#= link_to 'Forgot your password?', new_password_reset_path, class: 'btn btn-sm btn-default' %>
  <% end %>

app/views/user_sessions/new.html.erb
<h1 style="text-align: center">Sign Up Or Login</h1>

<!--
http://stackoverflow.com/questions/35222966/bootstrap-3-two-columns-in-container-with-100-width-backgrounds
<style>
  .row {
  background-color: #e1e2e4;
  background-image: url('image.jpg');
  background-repeat: no-repeat;
  background-size: 50% 100%;
  }
  </style>
-->
<div class="row">
<div class="container-fluid">
    <div class="col-xs-6">
        <%= render :partial => "login"%>
    </div>

    <div class="col-xs-6">
        <%= render :partial => "sign_up"%>
    </div>
</div>
</div>

<!--
  <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4">
                  <%= render :partial => "login"%>
                </div>
                <div class="col-lg-4 col-lg-offset-4">
                  <%= render :partial => "sign_up"%>
                </div>
            </div>
         </div>
-->
<!--
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <h2>Login</h2>
            <%#= render :partial => "login"%>
            
        </div>
        <div class="col-md-10">
            <h2>Sign Up</h2>
            <%#= render :partial => "sign_up"%>
        </div>
    </div>
</div>
-->